name: themovieapp
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.11.0
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.4
  dio: ^5.1.2
  equatable: ^2.0.5
  firebase_analytics: ^10.8.10
  firebase_core: ^2.27.1
  firebase_crashlytics: ^3.4.19
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  stream_transform: ^2.1.0
  shorebird_code_push: ^1.1.0
  restart_app: ^1.2.1

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.24.9 

flutter:

  uses-material-design: true
  generate: true

  assets:
    - .env
    - shorebird.yaml